[package]
name = "raytracer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
clap-verbosity-flag = "3.0.4"
display-info = "0.5.9"
env_logger = "0.11.11"
glam = { version = "0.33.3", features = ["debug-glam-assert"] }
image = "0.25.10"
log = "0.4.33"
rand = "0.10.2"
viuer = "0.11.0"
